name: MacOS/iOS/tvOS build

on: [push, pull_request]

jobs:
  precheks:
    runs-on: macos-14
    name: MacOS -> Pre-Checks

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Format validation
      shell: bash
      working-directory: ${{github.workspace}}/BuildTools/FormatValidation
      run: ./validate_format_mac.sh


  build:
    needs:   precheks
    runs-on: macos-14

    strategy:
      matrix:
        platform:   ["MacOS", "iOS", "tvOS"]
        build_type: ["Debug", "Release"]

        exclude:
          # Exclude tvOS-Debug
          - platform:   "tvOS"
            build_type: "Debug"

        include:
          - platform:   "MacOS"
            build_type: "Debug"
            cmake_args: "-DDILIGENT_BUILD_TESTS=ON"

          - platform:   "MacOS"
            build_type: "Release"
            # For some reason AVX2 causes invalid instruction exception on CI, so disable it
            cmake_args: "-DDILIGENT_BUILD_CORE_TESTS=ON -DDILIGENT_CLANG_RELEASE_COMPILE_OPTIONS=\"\""

          - platform:   "iOS"
            cmake_args: ""

          - platform:   "tvOS"
            cmake_args: ""

    name: MacOS -> ${{ matrix.platform }}-${{ matrix.build_type }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v3
      with:
        platform: ${{ matrix.platform }}

    - name: Configure CMake
      if:   success()
      uses: DiligentGraphics/github-action/configure-cmake@v3
      with:
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if:   success()
      uses: DiligentGraphics/github-action/build@v3
      with:
        target: install

    - name: DiligentCoreTest
      if:   ${{ success() && matrix.platform == 'MacOS' }}
      uses: DiligentGraphics/github-action/run-core-tests@v3

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if:   ${{ success() && matrix.build_type == 'Release' }}
      with:
        name: DiligentCore-${{ matrix.platform }}-${{ matrix.build_type }}
        path: |
          ${{env.DILIGENT_INSTALL_DIR}}
          !${{env.DILIGENT_INSTALL_DIR}}/**/*.a
        retention-days: 90
